name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_USER_PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Install local JAR
      run: mvn install:install-file -Dfile=lib/com.othr.swvigopay-0.0.1SNAPSHOT.jar -DgroupId=com.othr -DartifactId=swvigopay -Dversion=0.0.1SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    - name: Build deployable JAR
      run: mvn -B clean package spring-boot:repackage -P production
    - name: Build integration JAR for partner services
      run: |
        VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        cd target/classes
        TARGET_PATH="de/othr/bib48218/chat"
        jar cf "../chat-integration-${VERSION}.jar" "${TARGET_PATH}/entity/" "${TARGET_PATH}/service/IFSendMessage.class
    - name: Copy deployable JAR
      run: |
        mkdir packages
        mv target/*.jar packages/
    - name: Upload JARs
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: packages/
